from typing import Protocol

from app.schemas.items import ItemCreate, ItemRead, ItemUpdate


class ItemRepository(Protocol):
    def list_items(self) -> list[ItemRead]: ...
    def get_item(self, item_id: int) -> ItemRead | None: ...
    def create_item(self, data: ItemCreate) -> ItemRead: ...
    def update_item(self, item_id: int, data: ItemUpdate) -> bool: ...
    def delete_item(self, item_id: int) -> bool: ...
